name: "petanque tests"

on: [push]

jobs:
  build:

    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install ninja-build
    - name: Install dependencies (OSX)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install ninja
    - name: CMake
      working-directory: petanque
      run: |
        mkdir build
        cd build && cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja ..
    - name: Build
      working-directory: petanque/build
      run: ninja
    - name: Tests
      working-directory: petanque/build
      run: ninja test
